### ISSUE TITLE
Pull access denied for e28007e9030b, repository does not exist

### ISSUE THREAD

**Issue by rafaelvelosoAZ** [msleal/asciivmssdashboard#4]
When I try to execute the command:
sudo docker run -i -t e28007e9030b /bin/bash

I'm facing this issue:

Unable to find image 'e28007e9030b:latest' locally
Error response from daemon: pull access denied for e28007e9030b, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by msleal** [comment]
Hi,
  This does not seems to be an issue with the image, because it is stating that the image does not exist in your local docker system: Unable to find image 'e28007e9030b:latest' locally.
   First you need to download the image from my repo: https://hub.docker.com/repository/docker/msleal/asciivmssdashboard
    Anyway, this image I have created when there was no package for easy installation (it has an old version of the asciivmssdashboard on it), and I left it here for reference only (as it should work). But the preferred way to install the tool nowadays is just: pip install asciivmssdashboard.
   Thanks.
